/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CacheRouteImport } from './routes/cache'
import { Route as DurableObjectsRouteImport } from './routes/durable-objects'
import { Route as MangadexLibraryRouteImport } from './routes/mangadex-library'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as RequestsRouteImport } from './routes/requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRoute = CacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const DurableObjectsRoute = DurableObjectsRouteImport.update({
  id: '/durable-objects',
  path: '/durable-objects',
  getParentRoute: () => rootRouteImport,
} as any)
const MangadexLibraryRoute = MangadexLibraryRouteImport.update({
  id: '/mangadex-library',
  path: '/mangadex-library',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/durable-objects': typeof DurableObjectsRoute
  '/mangadex-library': typeof MangadexLibraryRoute
  '/operations': typeof OperationsRoute
  '/registry': typeof RegistryRoute
  '/requests': typeof RequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/durable-objects': typeof DurableObjectsRoute
  '/mangadex-library': typeof MangadexLibraryRoute
  '/operations': typeof OperationsRoute
  '/registry': typeof RegistryRoute
  '/requests': typeof RequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cache': typeof CacheRoute
  '/durable-objects': typeof DurableObjectsRoute
  '/mangadex-library': typeof MangadexLibraryRoute
  '/operations': typeof OperationsRoute
  '/registry': typeof RegistryRoute
  '/requests': typeof RequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cache'
    | '/durable-objects'
    | '/mangadex-library'
    | '/operations'
    | '/registry'
    | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache'
    | '/durable-objects'
    | '/mangadex-library'
    | '/operations'
    | '/registry'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/cache'
    | '/durable-objects'
    | '/mangadex-library'
    | '/operations'
    | '/registry'
    | '/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CacheRoute: typeof CacheRoute
  DurableObjectsRoute: typeof DurableObjectsRoute
  MangadexLibraryRoute: typeof MangadexLibraryRoute
  OperationsRoute: typeof OperationsRoute
  RegistryRoute: typeof RegistryRoute
  RequestsRoute: typeof RequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/durable-objects': {
      id: '/durable-objects'
      path: '/durable-objects'
      fullPath: '/durable-objects'
      preLoaderRoute: typeof DurableObjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mangadex-library': {
      id: '/mangadex-library'
      path: '/mangadex-library'
      fullPath: '/mangadex-library'
      preLoaderRoute: typeof MangadexLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CacheRoute: CacheRoute,
  DurableObjectsRoute: DurableObjectsRoute,
  MangadexLibraryRoute: MangadexLibraryRoute,
  OperationsRoute: OperationsRoute,
  RegistryRoute: RegistryRoute,
  RequestsRoute: RequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
